# Generated by Django 2.1.3 on 2018-11-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
