# Generated by Django 2.1.3 on 2018-12-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_activevideo_scheduledvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activevideo',
            old_name='generator',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='scheduledvideo',
            old_name='generator',
            new_name='video',
        ),
    ]
